dependencies:
  - matplotlib==3.1.3
  - networkx==2.4
  - numpy==1.18.1
  - pandas==1.0.1
  - requests=2.21.0
  - scikit-learn==0.22.1
  - statsmodels==0.11.1
  - tqdm==4.46.0
  - watermark==2.0.2
  - pygraphviz==1.5
  - pydot==1.4.1